-- R2.5 SYNTHETIC TESTS ONLY. Run in an interactive mysql session, not as migration.
-- Expected errors are documented before individual statements. No --force.
-- Scope must be rehab_r2_validation. All rows roll back; AUTO_INCREMENT gaps remain.
SELECT 'SCOPE', DATABASE();
SET NAMES utf8mb4;
SET SESSION time_zone='+00:00';
START TRANSACTION;

INSERT INTO users(email,role) VALUES ('r25-a@example.invalid','PATIENT');
SET @u1=LAST_INSERT_ID();
INSERT INTO users(email,role) VALUES ('r25-b@example.invalid','PATIENT');
SET @u2=LAST_INSERT_ID();
SELECT 'A01',IF((SELECT COUNT(*) FROM users WHERE id IN(@u1,@u2) AND account_id IS NULL AND google_subject IS NULL AND friend_code IS NULL AND password IS NULL)=2,'PASS','FAIL');
UPDATE users SET account_id='R25Case1',google_subject='r25-subject-A' WHERE id=@u1;
SELECT 'A02',IF((SELECT account_id_normalized FROM users WHERE id=@u1)='r25case1','PASS','FAIL');
SELECT 'E01_expected_1062';
UPDATE users SET account_id='r25case1' WHERE id=@u2;
SELECT 'A03',IF((SELECT account_id FROM users WHERE id=@u2) IS NULL,'PASS','FAIL');
SELECT 'E02_expected_1062';
UPDATE users SET google_subject='r25-subject-A' WHERE id=@u2;
UPDATE users SET google_subject='r25-subject-a' WHERE id=@u2;
SELECT 'A04',IF((SELECT COUNT(DISTINCT google_subject) FROM users WHERE id IN(@u1,@u2))=2,'PASS','FAIL');
SELECT 'E03_expected_1062';
INSERT INTO users(email,role) VALUES ('R25-A@example.invalid','PATIENT');
SELECT 'A05',IF((SELECT COUNT(*) FROM users)=2,'PASS','FAIL');

INSERT INTO users(email,role) VALUES ('r25-reset@example.invalid','PATIENT');
SET @ur=LAST_INSERT_ID();
INSERT INTO password_reset_requests(id,user_id,code_hash,expires_at,created_at) VALUES ('r25-reset-1',@ur,REPEAT('0',64),UTC_TIMESTAMP(6)+INTERVAL 10 MINUTE,UTC_TIMESTAMP(6));
SELECT 'E04_expected_1062';
INSERT INTO password_reset_requests(id,user_id,code_hash,expires_at,created_at) VALUES ('r25-reset-2',@ur,REPEAT('1',64),UTC_TIMESTAMP(6)+INTERVAL 10 MINUTE,UTC_TIMESTAMP(6));
UPDATE password_reset_requests SET consumed_at=UTC_TIMESTAMP(6) WHERE id='r25-reset-1';
INSERT INTO password_reset_requests(id,user_id,code_hash,expires_at,created_at) VALUES ('r25-reset-2',@ur,REPEAT('1',64),UTC_TIMESTAMP(6)+INTERVAL 10 MINUTE,UTC_TIMESTAMP(6));
INSERT INTO password_reset_requests(id,user_id,code_hash,expires_at,consumed_at,created_at) VALUES ('r25-reset-old',@ur,REPEAT('2',64),UTC_TIMESTAMP(6)-INTERVAL 1 DAY,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
SELECT 'A06',IF((SELECT COUNT(*) FROM password_reset_requests WHERE user_id=@ur)=3 AND (SELECT COUNT(*) FROM password_reset_requests WHERE active_user_id=@ur)=1 AND (SELECT COUNT(*) FROM password_reset_requests WHERE user_id=@ur AND active_user_id IS NULL)=2,'PASS','FAIL');
SELECT 'A07',IF((SELECT COUNT(*) FROM password_reset_requests WHERE user_id=@ur AND failed_attempts=0)=3,'PASS','FAIL');
DELETE FROM users WHERE id=@ur;
SELECT 'A08',IF((SELECT COUNT(*) FROM password_reset_requests WHERE user_id=@ur)=0,'PASS','FAIL');

SET @unicode=CONVERT(UNHEX('E5BEA9E581A5F09FA6B5') USING utf8mb4);
INSERT INTO exercise(exercise_name,description) VALUES (@unicode,'fixture');
SET @exercise=LAST_INSERT_ID();
SET SESSION time_zone='+08:00';
SET @before_utc=UTC_TIMESTAMP(6);
INSERT INTO exercise_result(user_id,exercise_id,rep_count,is_complete) VALUES (@u1,@exercise,1,NULL);
SET @result=LAST_INSERT_ID();
SELECT 'A09',IF((SELECT created_at FROM exercise_result WHERE id=@result) BETWEEN @before_utc AND UTC_TIMESTAMP(6) AND ABS(TIMESTAMPDIFF(SECOND,(SELECT created_at FROM exercise_result WHERE id=@result),NOW(6))-28800)<5,'PASS','FAIL');
SET SESSION time_zone='+00:00';
SELECT 'A10',IF((SELECT HEX(exercise_name) FROM exercise WHERE id=@exercise)='E5BEA9E581A5F09FA6B5','PASS','FAIL');
SELECT 'E05_expected_3819';
UPDATE exercise_result SET is_complete=2 WHERE id=@result;
SELECT 'A11',IF((SELECT is_complete FROM exercise_result WHERE id=@result) IS NULL,'PASS','FAIL');
SELECT 'E06_expected_1452';
INSERT INTO exercise_result(user_id,exercise_id,rep_count) VALUES (-999,@exercise,1);
SELECT 'E07_expected_1451';
DELETE FROM users WHERE id=@u1;
SELECT 'A12',IF((SELECT COUNT(*) FROM users WHERE id=@u1)=1,'PASS','FAIL');

SELECT 'E08_expected_3819';
INSERT INTO chat_conversations(participant_one_id,participant_two_id,conversation_type,created_at,updated_at) VALUES (@u2,@u1,'PEER',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
SELECT 'E09_expected_3819';
INSERT INTO chat_conversations(participant_one_id,participant_two_id,conversation_type,created_at,updated_at) VALUES (@u1,@u2,'INVALID',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
INSERT INTO chat_conversations(participant_one_id,participant_two_id,conversation_type,created_at,updated_at) VALUES (@u1,@u2,'PEER',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6));
SET @chat=LAST_INSERT_ID();
INSERT INTO chat_messages(conversation_id,sender_id,text,sent_at) VALUES (@chat,@u1,@unicode,UTC_TIMESTAMP(6));
SELECT 'A13',IF((SELECT COUNT(*) FROM chat_conversations)=1 AND (SELECT HEX(text) FROM chat_messages WHERE conversation_id=@chat)='E5BEA9E581A5F09FA6B5','PASS','FAIL');
SELECT 'E10_expected_1451';
DELETE FROM chat_conversations WHERE id=@chat;

SELECT 'E11_expected_3819';
INSERT INTO rehab_plans(plan_id,patient_id,created_by,plan_date,condition_type) VALUES ('r25-invalid',@u1,'fixture','2026-10-02','INVALID');
INSERT INTO rehab_plans(plan_id,patient_id,created_by,plan_date,condition_type) VALUES ('r25-plan',@u1,'fixture','2026-10-02','fracture');
SET @plan=LAST_INSERT_ID();
SELECT 'E12_expected_3819';
INSERT INTO rehab_plan_items(rehab_plan_id,exercise_id,item_order,sets,reps_per_set) VALUES (@plan,'string-action',-1,1,1);
SELECT 'E13_expected_3819';
INSERT INTO rehab_plan_items(rehab_plan_id,exercise_id,item_order,sets,reps_per_set) VALUES (@plan,'string-action',0,0,1);
SELECT 'E14_expected_3819';
INSERT INTO rehab_plan_items(rehab_plan_id,exercise_id,item_order,sets,reps_per_set) VALUES (@plan,'string-action',0,1,0);
INSERT INTO rehab_plan_items(rehab_plan_id,exercise_id,item_order,sets,reps_per_set) VALUES (@plan,'string-action',0,1,2);
SELECT 'A14',IF((SELECT done FROM rehab_plan_items WHERE rehab_plan_id=@plan)=0 AND (SELECT COUNT(*) FROM rehab_plan_items)=1,'PASS','FAIL');
SELECT 'E28_expected_3819';
UPDATE rehab_plan_items SET done=2 WHERE rehab_plan_id=@plan;
DELETE FROM rehab_plans WHERE id=@plan;
SELECT 'A15',IF((SELECT COUNT(*) FROM rehab_plan_items WHERE rehab_plan_id=@plan)=0,'PASS','FAIL');

SET @large_text=CONCAT('{"note":"',REPEAT(@unicode,12000),'"}');
INSERT INTO custom_rehab_exercises(id,name,description,created_by_therapist_id,created_at,updated_at,repetitions,sets,hold_seconds,rest_seconds,duration,keyframes_json,evaluation_rules_json) VALUES ('r25-custom',@unicode,'fixture',@u2,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),2,2,1.5,3,6,@large_text,'[]');
SELECT 'A16',IF((SELECT SHA2(keyframes_json,256) FROM custom_rehab_exercises WHERE id='r25-custom')=SHA2(@large_text,256) AND (SELECT OCTET_LENGTH(keyframes_json) FROM custom_rehab_exercises WHERE id='r25-custom')>65535,'PASS','FAIL');
INSERT INTO custom_exercise_assignments(custom_exercise_id,patient_id,assigned_by_therapist_id,assigned_at,is_active) VALUES ('r25-custom',@u1,@u2,UTC_TIMESTAMP(6),1);
SELECT 'E15_expected_3819';
UPDATE custom_exercise_assignments SET is_active=2;
INSERT INTO exercise_assignments(exercise_id,patient_id,assigned_by_therapist_id,assigned_at,is_active) VALUES (@exercise,@u1,@u2,UTC_TIMESTAMP(6),1);
SELECT 'E16_expected_3819';
UPDATE exercise_assignments SET is_active=2;

INSERT INTO training_history(user_id,action_name,difficulty,duration_seconds,target_reps,mistake_count,client_timestamp,created_at) VALUES (@u1,@unicode,1,10,2,0,'r25-fixture-time',UTC_TIMESTAMP(6));
SET @history=LAST_INSERT_ID();
SET @binary=REPEAT(UNHEX('00017FFF'),20000);
INSERT INTO training_history_video(history_id,content_type,file_size,video_data,created_at) VALUES (@history,'video/mp4',OCTET_LENGTH(@binary),@binary,UTC_TIMESTAMP(6));
SELECT 'A17',IF((SELECT HEX(SUBSTRING(video_data,1,4)) FROM training_history_video WHERE history_id=@history)='00017FFF' AND (SELECT SHA2(video_data,256) FROM training_history_video WHERE history_id=@history)=SHA2(@binary,256) AND (SELECT OCTET_LENGTH(video_data) FROM training_history_video WHERE history_id=@history)=80000,'PASS','FAIL');
SELECT 'E17_expected_3819';
UPDATE training_history_video SET file_size=0 WHERE history_id=@history;
DELETE FROM training_history WHERE id=@history;
SELECT 'A18',IF((SELECT COUNT(*) FROM training_history_video WHERE history_id=@history)=0,'PASS','FAIL');
INSERT INTO user_avatars(user_id,mime_type,image_data,source_type) VALUES (@u1,'image/png',@binary,'CUSTOM');
SELECT 'A19',IF((SELECT SHA2(image_data,256) FROM user_avatars WHERE user_id=@u1)=SHA2(@binary,256),'PASS','FAIL');
SELECT 'E18_expected_3819';
UPDATE user_avatars SET source_type='INVALID' WHERE user_id=@u1;

INSERT INTO research_consents(user_id,subject_id,consent_version,active,consented_at) VALUES (@u1,'r25-subject-1','fixture-v1',1,UTC_TIMESTAMP(6));
SELECT 'E19_expected_3819';
UPDATE research_consents SET active=2;
SELECT 'E20_expected_1062';
INSERT INTO research_consents(user_id,subject_id,consent_version,active) VALUES (@u2,'r25-subject-1','fixture-v1',0);
INSERT INTO research_samples(id,participant_user_id,subject_id,client_sample_id,captured_at,uploaded_at,movement_side,camera_view,payload_json,client_payload_hash) VALUES ('r25-sample',@u1,'r25-subject-1','r25-client-sample',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'LEFT','FRONT',@large_text,REPEAT('0',64));
SELECT 'E21_expected_1062';
INSERT INTO research_samples(id,participant_user_id,subject_id,client_sample_id,captured_at,uploaded_at,movement_side,camera_view,payload_json,client_payload_hash) VALUES ('r25-duplicate',@u1,'r25-subject-1','r25-client-sample',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'LEFT','FRONT','{}',REPEAT('1',64));
SELECT 'E22_expected_1452';
INSERT INTO research_samples(id,participant_user_id,subject_id,client_sample_id,captured_at,uploaded_at,movement_side,camera_view,payload_json,client_payload_hash) VALUES ('r25-orphan',-999,'unlinked-logical-id','other',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'LEFT','FRONT','{}',REPEAT('1',64));
INSERT INTO research_annotations(sample_id,therapist_user_id,label,label_version,action_definition_version,status,updated_at) VALUES ('r25-sample',@u2,'NOT_EVALUABLE','fixture-v1','fixture-v1','DRAFT',UTC_TIMESTAMP(6));
SELECT 'A20',IF((SELECT revision FROM research_annotations WHERE sample_id='r25-sample')=0 AND (SELECT SHA2(payload_json,256) FROM research_samples WHERE id='r25-sample')=SHA2(@large_text,256),'PASS','FAIL');
SELECT 'E23_expected_1451';
DELETE FROM research_samples WHERE id='r25-sample';
INSERT INTO research_annotation_revisions(sample_id,revision,actor_user_id,annotator_user_id,label,label_version,action_definition_version,status,created_at) VALUES ('r25-sample',1,@u2,@u2,'NOT_EVALUABLE','fixture-v1','fixture-v1','DRAFT',UTC_TIMESTAMP(6)),('r25-sample',1,@u2,@u2,'NOT_EVALUABLE','fixture-v1','fixture-v1','DRAFT',UTC_TIMESTAMP(6));
SELECT 'A21',IF((SELECT COUNT(*) FROM research_annotation_revisions WHERE sample_id='r25-sample' AND revision=1)=2,'PASS','FAIL');
INSERT INTO research_grants(user_id,study_id,can_annotate,can_review,can_manage,updated_at) VALUES (@u2,'r25-study',1,0,0,UTC_TIMESTAMP(6));
SELECT 'E24_expected_1062';
INSERT INTO research_grants(user_id,study_id,can_annotate,can_review,can_manage,updated_at) VALUES (@u2,'r25-study',0,0,0,UTC_TIMESTAMP(6));
SELECT 'E25_expected_3819';
UPDATE research_grants SET can_annotate=2;
SELECT 'E26_expected_3819';
UPDATE research_grants SET can_review=2;
SELECT 'E27_expected_3819';
UPDATE research_grants SET can_manage=2;
INSERT INTO research_audit(actor_user_id,action,sample_id,created_at) VALUES (-999,'FIXTURE','nonexistent-sample',UTC_TIMESTAMP(6));
INSERT INTO research_retention_events(sample_id,reason,processed_at) VALUES ('deleted-fixture','FIXTURE',UTC_TIMESTAMP(6));
SELECT 'A22',IF((SELECT COUNT(*) FROM research_audit)=1 AND (SELECT COUNT(*) FROM research_retention_events)=1 AND (SELECT COUNT(*) FROM research_retention_policies)=0,'PASS','FAIL');

ROLLBACK;
SELECT 'A23',IF((SELECT COUNT(*) FROM users)=0 AND (SELECT COUNT(*) FROM exercise)=0 AND (SELECT COUNT(*) FROM research_samples)=0 AND (SELECT COUNT(*) FROM user_avatars)=0,'PASS','FAIL');
SELECT 'DONE_ROLLBACK';
